name: "Build Containers on Changes"

on:
  pull_request:
    branches:
      - main
 
jobs:
  check:
    name: Check for Changes
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tester: ["libabigail"]
    steps:
      - name: Checkout
        uses: actions/checkout@v2        
      - name: Look for changes in Dockerfiles
        id: changes
        run: |
            git fetch
            cd docker/${{ matrix.tester }}
            for dockerfile in $(git diff --name-only origin/main HEAD .); do
                printf "${dockerfile}\n"
            done
