name: "Build Containers on Changes"

on:
  pull_request:
    branches:
      - main
 
jobs:
  list-testers:
    name: Check for Changes
    runs-on: ubuntu-latest
    outputs:
      testers: ${{ steps.list.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2        
      - name: Save testers list
        id: list
        run: |
          cd testers
          testers=$(python -c 'import os, json; print(json.dumps(os.listdir(".")))')  
          echo "Found testers $testers"
          echo '::set-output name=matrix::$testers'

  build-containers:
    needs:
      - list-testers
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tester: ${{ fromJson(needs.list-testers.outputs.testers) }}
    name: Build ${{ matrix.tester }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2        
      - name: Test Building Changes
        env:
          # registry organization
          registry: quay.io/buildsi
        run: |
            git fetch
            printf "Looking for changes in tester ${{ matrix.tester }}\n"
            cd docker/${{ matrix.tester }}
            for dockerfile in $(git diff --name-only origin/main HEAD .); do
                if [ ! -f "$dockerfile" ]; then
                    printf "Dockerfile ${dockerfile} does not exist, skipping.\n"
                    continue
                fi
                # A version file must exist
                tester_dir=$(dirname $dockerfile)
                if [ ! -f "$tester_dir/versions" ]; then
                    printf "versions text file missing for $dockerfile."
                    exit 1
                fi
                versions=$(cat $tester_dir/versions)
                filename=$(basename $dockerfile)
                for version in ${versions}; do        
                    container=${{ env.registry }}/${{ matrix.tester }}:${version}
                    printf "Building ${dockerfile} with version ${version} to container ${container}\n"  
                    docker build -f ${filename} --build-arg LIBRARY_VERSION=${version} -t ${container} .
                done
            done
