name: Deploy test containers

on:
  pull_request: []
#    types: [labeled]

jobs:
  changes:
    runs-on: ubuntu-latest

  - id: files
    uses: jitterbit/get-changed-files@b17fbb00bdc0c0f63fcf166580804b4d2cdc2a42
    with:
      format: 'json'
  
  deploy-test-containers:
    needs:
      - changes
    runs-on: ubuntu-latest
    strategy:
      matrix:
        changed_file: ${{ fromJson(changes.files.outputs.added_modified) }}

    name: Check ${{ matrix.changed_file }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2        

      - name: Make Space For Build
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc

      - name: Build and Deploy Test Containers
        run: |
            echo ${{ secrets.DOCKER_PASSWORD }} | docker login quay.io -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
            echo "${{ matrix.changed_file }}"

#            pip install -r requirements.txt
#            root="${PWD}"
#            cd tests
#            for testyaml in $(git diff --name-only origin/main HEAD .); do
#                relpath=$(basename ${testyaml})
#                if [ ! -f "${relpath}" ]; then                
#                    printf "${relpath} does not exist.\n"
#                    continue
#                fi
#                if [ "$relpath" == "${{ matrix.test }}" ]; then                
#                    printf "Found changed test file ${testyaml}\n"
#                    python ../build-si-containers build --root "${root}" "${relpath}"
#                    python ../build-si-containers deploy --root "${root}" "${relpath}"
#                fi
#            done
#            cd ../
