name: Deploy test containers

on:
  pull_request: []
#    types: [labeled]

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      changed_file: ${{ steps.files.outputs.added_modified }}
    steps:
      - id: files
        uses: jitterbit/get-changed-files@b17fbb00bdc0c0f63fcf166580804b4d2cdc2a42
        with:
          format: 'json'
  
  deploy-test-containers:
    needs:
      - changes
    runs-on: ubuntu-latest
    strategy:
      matrix:
        changed_file: ${{ fromJson(needs.changes.outputs.changed_file) }}

    name: Check ${{ matrix.changed_file }}
    steps:
      - name: Continue if Test
        run: |
          # Continue if we have a changed tests file
          if [[ "${{ matrix.changed_file }}" = tests* ]]; then
            echo "::set-output name=continue::true"
            echo "::set-output name=container_test::true"
          fi          
          # Continue if we have a changed tester template
          if [[ "${{ matrix.changed_file }}" = docker* ]]; then
            echo "::set-output name=continue::true"
            echo "::set-output name=container_base::true"
          fi          

      - name: Checkout
        if: ${{ env.continue == 'true' }}
        uses: actions/checkout@v2        

      - name: Make Space For Build
        if: ${{ env.continue == 'true' }}
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc

      - name: Build and Deploy Test Containers
        if: ${{ env.container_test == 'true' }}
        run: |
            echo ${{ secrets.DOCKER_PASSWORD }} | docker login quay.io -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
            echo "${{ matrix.changed_file }}"
            pip install -r requirements.txt
            relpath=$(basename ${{ matrix.changed_file }})
            printf "Found changed test file ${{ matrix.changed_file }}\n"
            python build-si-containers build "${relpath}"
            python ../build-si-containers deploy --root "${root}" "${relpath}"
