name: "Run Tests on Changes"

on:
  pull_request:
    branches:
      - main
 

jobs:
  list-tests:
    name: List Tests
    runs-on: ubuntu-latest
    outputs:
      tests: ${{ steps.list.outputs.tests }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2        
      - name: Save tests list
        id: list
        run: |
          cd tests
          tests=$(python -c 'import os, json; print(json.dumps(os.listdir(".")))')  
          echo "Found tests $tests"
          echo "::set-output name=tests::${tests}"
  
  build-test-containers:
    needs:
      - list-tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test: ${{ fromJson(needs.list-tests.outputs.tests) }}
    name: Build ${{ matrix.test }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2        
      - name: Build Test Containers
        run: |
            git fetch
            printf "Looking for changes in test ${{ matrix.test }}\n"
            pip install -r requirements.txt
            root=${PWD}
            cd tests
            for testyaml in $(git diff --name-only origin/main HEAD .); do
                if [ ! -f "${relpath}" ]; then                
                    printf "${relpath} does not exist.\n"
                    continue
                fi
                relpath=$(basename ${testyaml})
                if [ "$relpath" == "${{ matrix.test }}" ]; then                
                    printf "Found changed test file ${testyaml}\n"
                    python ../build-si-containers test --root "${root}" "${relpath}"
                fi
            done
